
ccp4_mtz_types.h:       	../core/container_hkl.h 

ccp4_mtz_types.o:       	ccp4_mtz_types.cpp ccp4_mtz_types.h 

ccp4_mtz_io.h:          	ccp4_mtz_types.h 

ccp4_mtz_io.o:          	ccp4_mtz_io.cpp ccp4_mtz_io.h 

ccp4_map_io.h:          	../core/container_map.h 

ccp4_map_io.o:          	ccp4_map_io.cpp ccp4_map_io.h 

